//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 奈班级学生管理系统.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayTable
    {
        public int PayID { get; set; }
        public string PayStely { get; set; }
        public string PayMoney { get; set; }
        public Nullable<int> Paystate { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string Time { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
