//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 奈班级学生管理系统.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Grade = new HashSet<Grade>();
            this.PayTable = new HashSet<PayTable>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string Tell { get; set; }
        public string Sex { get; set; }
        [Required(ErrorMessage = "学号不能为空")]
        public string StudentNum { get; set; }
        [Required(ErrorMessage = "密码不能为空")]
        public string StudentPwd { get; set; }
        public string Nation { get; set; }
        public string PoliticsStatus { get; set; }
        public string Position { get; set; }
        public string Major { get; set; }
        public string RecruitType { get; set; }
        public string Dorm { get; set; }
        public string Hometown { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> TeacherID { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Grade> Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayTable> PayTable { get; set; }
    }
}
